# Site settings
title: trademon
email: paul.jedich@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "96items.com" # the base hostname & protocol for your site

twitter_username:
github_username: pjedich

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman